# Generated by Django 5.1.6 on 2025-02-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('callorise', models.IntegerField(blank=True)),
            ],
        ),
    ]
