# Generated by Django 5.1.6 on 2025-02-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeAndProduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatigoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
