# Generated by Django 5.1.6 on 2025-02-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeAndProduct', '0002_catigoryrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('discription', models.TextField(blank=True)),
                ('cooking_steps', models.TextField(blank=True)),
                ('cooking_time', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
