# Generated by Django 5.1.6 on 2025-02-10 21:00

import RecipeAndProduct.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeAndProduct', '0003_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_dish',
            field=models.ImageField(blank=True, null=True, upload_to=RecipeAndProduct.models.image_path_name),
        ),
    ]
